### PR TITLE
Homework5: Lazar Maxim

### PR DESCRIPTION
**Pull request by Wilreyyt**

### CODE REVIEW

**Comment by Stml89** [comment]
Can not find the file with HW5 =(
Please do not close PR, fix it and push updates. PR will be updated automatically

**Review by Stml89 — CHANGES_REQUESTED** [review]
See above

**Review by Stml89 — CHANGES_REQUESTED** [review]
HW looks good, but linters still fails

**Comment by Wilreyyt** [comment]
I fixed all linters but "Auto assign" didn't work here because it reacts only on NEW PR

**Review by Stml89 — APPROVED** [review]

**Pull request merged**
